### ISSUE TITLE
Постоянно активный предзагрузчик

### ISSUE THREAD

**Issue by DispenserBro** [rozenrod/LiteLibria#30]
![image](https://github.com/rozenrod/LiteLibria/assets/26117737/de848ff1-d267-47a0-a4fa-49b8cac5b632)

###Шаги для повторения:
 1. Перейти на сайт https://litelibria.com

###Ожидаемый результат:
 - Скрытие предзагрузчика по прошествии времени

###Наблюдаемый результат:
 - Постоянно активный предзагрузчик

Насколько я понял, это происходит из-за битых ссылок на API/некорректной работы API, так как при скрытии прездагрузчика через инструменты разработчика не отобажаются изображения с карточек тайтлов

###Устройства/браузеры, на которых наблюдается результат

| Устройство | Браузер | Версия браузера |
| :---         |     :---:      |          ---: |
| PC (Manjaro) | Chromium | 112.0.5615.165-1 |
| PC (Manjaro) | Firefox | 113.0-0.1 |
| PC (Windows 11) | Google Chrome | 113.0.5672.94 |
| PC (Windows 11) | Yandex browser | 23.3.3.719 |
| POCO M3 Pro | Google Chrome | 113.0.5672.76 |
| POCO M3 Pro | Yandex Browser | 23.3.7.24 |
| POCO M3 Pro | Opera GX | 2.0.8 |
| Honor 20 | Google Chrome | 113.0.5672.76 |

**Comment by rozenrod** [comment]
А оригинальный сайт anilibria.tv грузится нормально или требуется использовать зеркала ?

**Comment by rozenrod** [comment]
А оригинальный сайт anilibria.tv грузится нормально или требуется использовать зеркала ?

**Comment by DispenserBro** [comment]
@rozenrod оригинальный сайт без проблем грузится на всех устройствах

**Comment by rozenrod** [comment]
@DispenserBro, для уточнения, прошу скрин ошибок в консоли. Если использовать VPN, то та же ошибка. 

*чтоб быстро закрыть окно загрузки, то можно просто нажать на Рам (Рем).

**Comment by DispenserBro** [comment]
@rozenrod 
![image](https://github.com/rozenrod/LiteLibria/assets/26117737/a5c75aa1-1b63-4eb9-b493-4b6750c88f34)

Еще дополню, что с месяц назад вообще без проблем все работало, недели две назад периодически начал этот баг проявляться, сейчас на постоянке

**Comment by rozenrod** [comment]
@DispenserBro, попробуй сейчас открыть сайт в режиме инкогнито, и было б неплохо проверить все же VPN.

**Comment by DispenserBro** [comment]
@rozenrod И в инкогнито и так теперь все ок, c VPN тоже 👍

**Comment by DispenserBro** [comment]
Спасибо за помощь! Буду у провайдера уточнять что да как
